выполнены задания NotificationMessage + SortableTable
js-tasks-ru/js-20230117_maximplotnikov pull request #4
Opened 2023-02-03 14:03 UTC by plotnikovma

2023-02-03 14:04 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-02-04 12:56 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-05 08:38 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-06 11:37 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      return;
good 👍

2023-02-06 11:37 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  static notification;
good 👍
лайк за статическое св-во

2023-02-06 11:38 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  show(place = document.body) {
👍 good

2023-02-06 11:38 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    for (let subElement of elements) {
`const`

2023-02-06 11:38 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    for (let subElement of elements) {
`const`

2023-02-06 11:39 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +      const columnHeader = event.target.closest('div');
good 👍
лайк за использование `event delegation` подхода

2023-02-06 11:39 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    return data.sort((a, b) => {
👍 good

2023-02-06 11:40 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    if (Tooltip.instance) {return Tooltip.instance;}
👍 good 
лайк за использование статического св-ва

2023-02-06 11:42 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    document.addEventListener('pointermove', (event) => this.pointerMoveElement(event));
🔴 please don't do this
пожалуйста, подумайте как добавить обработчик `pointermove` только в момент когда курсор находится над эл-том у которого есть тултип

2023-02-06 11:42 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    const shift = 10;
👍 good

2023-02-06 11:43 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    document.removeEventListener('pointerover', this.pointerOverElement);
почему удаляется только один обработчик?

2023-02-06 11:43 UTC, dosandk requested changes
пожалуйста внесите правки в решение `Tooltip`

2023-02-07 14:11 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-07 14:27 UTC, dosandk approved these changes
👍 good

2023-02-07 14:28 UTC, merged